CREATE TABLE t(s SERIAL PRIMARY KEY, v VARCHAR(32));
INSERT INTO t(v) VALUES ('one'), ('two'), ('three') RETURNING *;
UPDATE t SET v=CONCAT(v,v) WHERE s=2 RETURNING v;
DELETE FROM t WHERE s=2 RETURNING v;
